### ISSUE TITLE
Linux Makefiles

### ISSUE THREAD

**Issue by servusdei2018** [maxon887/Cross#25]
I would really appreciate some Makefiles for Linux.

**Comment by maxon887** [comment]
Sorry man, not planning to add sopport for linux.

**Comment by servusdei2018** [comment]
Has anyone tried compiling it with g++ or mingw?

**Comment by maxon887** [comment]
Probably not, if you are interested i can help you to build it. It shouldn't be very difficult, basically you need to override coupe of classes

**Comment by servusdei2018** [comment]
That would be awesome! :)

**Comment by maxon887** [comment]
connect with me via facebook for fast replies
https://www.facebook.com/profile.php?id=100001651879786
